In [1]:
import geopandas as gpd
import pandas as pd
from sqlalchemy import create_engine
from geoalchemy2 import Geometry
from shapely.geometry import MultiPolygon

In [2]:
survey_data = gpd.read_file("Fish_-_High_Mountain_Lakes_[ds102].geojson")

In [3]:
lake_names = {}
for entry in survey_data.itertuples():
    if not pd.isna(entry.LakeName):
        lake_names[entry.CaLakesID] = entry.LakeName

In [4]:
gdf = gpd.read_file("California_Lakes.geojson")

In [5]:
table_data = gpd.GeoDataFrame({
    #table values are as follows:
    #name
    "name": gdf["NAME"],
    #boundary
    "boundary": gdf['geometry'],
    #nominal_coords (todo: rename centroid to nominal_coords
    "nominal_coords": gpd.points_from_xy(
        gdf["LON_NAD83"],
        gdf["LAT_NAD83"]
    ),
    #elevation
    "elevation": gdf["elev_ft"],
    #surface_area
    "surface_area": gdf["sfc_acres"],
    #state
    "state": "CA",
    #county
    "county": gdf["COUNTY"],
    #state_id
    "state_id": gdf["DFGWATERID"],
    #gnis_id
    "gnis_id": gdf["GNIS_ID"] 
    
    }, geometry="boundary", crs = gdf.crs )



def ensure_multipolygon(geom):
    if geom.geom_type == "Polygon":
        return MultiPolygon([geom])
    return geom

table_data["boundary"] = table_data["boundary"].apply(ensure_multipolygon)

In [6]:
#update the names of the lakes if we have a beter option
for row in table_data.itertuples():
    current_name = row.name
    table_data.loc[row.Index, "name"] = current_name.replace("#", "")
    current_name = table_data.loc[row.Index, "name"]

    ca_lake_id = row.state_id
    if (ca_lake_id in lake_names):
        survey_name = lake_names[ca_lake_id]
        if (current_name == " "):
            #if there is no name in lakes DB, but there is one in the survey, use the survey name
            table_data.loc[row.Index, "name"] = survey_name
            print("set empty name to", survey_name)
        elif (current_name != survey_name):
            #if the name doesn't end in a number but the survey name does
            #that almost always means that the survey name is more specific
            #(e.g. Maggie Lakes vs Maggie Lake 1)
            #similarly, If the name ends in an "s" but the survey does not, that often means
            #the survey is more specific (e.g., Maggie Lakes vs Maggie Lake, upper)
            if ( (current_name[-1].isalpha() and not survey_name[-1].isalpha()) 
               or current_name[:-1] in survey_name):
                print(f"renaming {current_name} to {survey_name}")
                table_data.loc[row.Index, "name"] = survey_name
            else:
                print(f" {current_name} has alias {survey_name}")
    
    
    #as a final layer, see if we can fill in any empty names from the GNIS name
    current_name = table_data.loc[row.Index, "name"]
    gnis_name = gdf.loc[row.Index, "GNIS_NAME"]
    if (current_name == " " and gnis_name != " "):
        print("set empty name to GNIS name: ", gnis_name)
        table_data.loc[row.Index, "name"] = gnis_name

 Raspberry Lake has alias Raspberry lake
 Devils Punchbowl has alias Devil's Punchbowl Lake
 Lake Anna has alias Anna
 Lower Bear Lake has alias Bear Lake, Lower
renaming Bear Lake to Bear Lake, Marble Mountain
 Upper Wright Lake has alias Wright Lake, Upper
 Lower Wright Lake has alias Wright Lake, Lower
 Blue Granite Lake has alias Granite Lake, Blue
 Green Granite Lake has alias Granite Lake, Green
 Gold Granite Lake has alias Granite Lake
 Little Elk Lake has alias Elk Lake, Little
 Lower Sky High Lake has alias Sky High Lake, Lower
 Upper Sky High Lake has alias Sky High Lake, Upper
 Lake Of The Island has alias Lake of the Island
 Little Hancock Lake has alias Hancock Lake, Little
 Upper English Lake has alias English Lake, Upper
 Ruffey Lakes 1 has alias Ruffey Lake, Lower
 Ruffey Lakes 2 has alias Ruffey Lake, Upper
renaming Hidden Lakes to Hidden Lake 1
renaming Deadfull Lakes to Deadfall Lake, Upper (Trinity Divide)
renaming West Park Lakes to West Park Lake, Middle
renaming West Park Lakes to West Park Lake, Lower
renaming Caldwell Lakes to Caldwell Lake 1
renaming Caldwell Lakes to Caldwell Lake, Middle
renaming Twin Lakes to Twin Lake, West
renaming Twin Lakes to Twin Lake, East
 Upper Albert Lake has alias Albert Lake, Upper
renaming Horse Range Lakes to Horse Range Lakes 1
 Lower Russian Lake has alias Russian Lake, Lower
renaming Mill Creek Lake to Mill Creek Lake, West
renaming Big Marshy Lake to Marshy Lake, Big (Salmon Scott)
renaming Little Marshy Lake to Marshy Lake, Little (Salmon Scott)
 Little Castle Lake has alias Castle Lake, Little
renaming Black Rock Lake to Black Rock Lake, Yolla Bolly
renaming Mavis Lake to Mavis Lake (Salmon Scott)
 Lower Cliff Lake has alias Cliff Lake, Lower
 Upper Seven Lake has alias Seven Lake, Upper
 Lower Seven Lake has alias Seven Lake, Lower
 Lake Helen has alias Helen Lake
renaming Grouse Lake to Grouse Lake (Trinity Divide)
 Devils Lake has alias Devil's Lake
 Little Caribou Lake has alias Caribou Lake, Little
 Little South Fork Lake has alias South Fork Lake, Little
renaming Shimmy Lake to Shimmy Lake (Trinity Alps)
renaming Ward Lake to Ward Lake (Trinity Alps)
renaming Horseshoe Lake to Horseshoe Lake (Trinity Divide)
renaming Twin Lakes to Twin Lakes, Lower, Trinity Alps
renaming Lake Eleanor to Eleanor Lake (Trinity Alps)
 L Lake has alias El Lake
renaming Canyon Creek Lakes to Canyon Creek Lake, Upper (Trinity Alps)
renaming Papoose Lake to Papoose Lake (Trinity Alps)
renaming Canyon Creek Lakes to Canyon Creek Lake, Lower (Trinity Alps)
renaming Granite Lake to Granite Lake (Trinity Alps)
renaming Boulder Creek Lakes to Boulder Creek Lakes 2
 Boulder Creek Lakes has alias Boulder Lake, Canyon Creek, Trinity Alps
renaming Forbidden Lakes to Forbidden Lakes 1
renaming Boulder Creek Lakes to Boulder Creek Lakes 1
renaming Forbidden Lakes to Forbidden Lakes 2
renaming Deer Lake to Deer Lake (Trinity Alps)
renaming Diamond Lake to Diamond Lake (Trinity Alps)
renaming Rush Creek Lakes to Rush Creek Lake, Middle (Trinity Alps)
renaming Twin Lakes to Twin Lake
 Cowboy Lake has alias Hourglass Lake
 North Divide Lake has alias Divide Lake, North
renaming Hidden Lakes to Hidden Lake 2
renaming Hidden Lakes to Hidden Lake 4
renaming Hidden Lakes to Hidden Lake 5
renaming Cuddihy Lakes to Cuddihy Lakes 2
renaming Cuddihy Lakes to Cuddihy Lakes 4
 Stoddard Lake, Upper has alias Stoddard Lake Upper, Salmon Scott
renaming Holland Lake to Holland Lake (Salmon Scott)
renaming Caldwell Lakes to Caldwell Lake, Lower
renaming South Fork Lakes to South Fork Lakes 1
renaming Seven Up Lake to Seven Up Lake (Trinity Alps)
renaming Hidden Lakes to Hidden Lake 3
renaming Rush Creek Lake, Upper to Rush Creek Lake, Upper (Trinity Alps)
 Lake Almanor has alias Almanor, Lake
renaming Grassy Lakes to Grassy Lakes 1
renaming Grassy Lakes to Grassy Lakes 2
renaming Three Lakes to Three Lakes, Middle
renaming Three Lakes to Three Lakes, Upper
renaming Cole Creek Lakes to Cole Creek Lake (North)
 Upper Mud Lake has alias Mud Lake, Upper
 Little Bear Lake has alias Bear Lake, Little
 Little Gold Lake has alias Gold Lake, Little
 Lower Salmon Lake has alias Salmon Lake, Lower
 Lower Rock Lake has alias Rock Lake, Lower
set empty name to Talbot Lake
set empty name to Virginia Lake
set empty name to Johanna Lake
 Upper Relief Valley Lakes has alias Relief Lake, North
renaming Lewis Lakes to Lewis Lake, Lower
renaming Lewis Lakes to Lewis Lake, Middle
 Lake Of The Woods has alias Lake of the Woods
renaming Lindsey Lakes to Lindsey Lake, Upper
renaming Lindsey Lakes to Lindsey Lake, Lower
 Five Lakes Basin has alias Elaine Lake
 Five Lakes Basin has alias Meyers Lake
 Shotgun Lake has alias Shotgun Meadow Lake
 Devils Oven Lake has alias Lost Lake
 Upper Lola Montez Lake has alias Lola Montez Lake, Upper
 Eagle Lakes has alias Jakes Lake
 Lower Lola Montez Lake has alias Lola Montez Lake, Lower
 Azalea Lake has alias Azalea lake
 Loch Leven Lakes (lower) has alias Loch Leven, Lower
renaming Five Lakes to Five Lakes 1
renaming Five Lakes to Five Lakes 2
 Lake Sylvia has alias Sylvia Lake
renaming Cole Creek Lakes to Cole Creek Lake (South)
renaming Wire Lakes to Wire Lake, North
renaming Grouse Lakes to Grouse Lake, Upper
renaming Grouse Lakes to Grouse Lake, Lower
 4-Q Lakes 3 has alias Q Lake, Upper
 4-Q Lakes 5 has alias Q Lake, Lower
 4-Q Lakes 4 has alias Q Lake, Middle
 Lake No 5 has alias Number 5 Lake
renaming Angora Lakes to Angora Lakes 2 (AKA:Angora Lake, Lower)
renaming Angora Lakes to Angora Lakes 3 (AKA:Angora Lake, Upper)
 Lake Margery has alias Margery Lake
set empty name to Baron Lake
 Lake Audrian has alias Audrian Lake
renaming Four Lakes to Four Lakes 4 (AKA:Four Lakes, Upper)
renaming Four Lakes to Four Lakes 2 (AKA:Four Lakes, Middle)
iddle)
renaming Four Lakes to Four Lakes 1
 Lower Sunset Lake has alias Sunset Lake, Lower
set empty name to Blixie Lake
renaming Tamarack Lakes to Tamarack Lakes 2
set empty name to Kaneen Lake
 Mcmillan Lake has alias McMillan Lake
set empty name to Papoose Lake
renaming Tamarack Lakes to Tamarack Lakes 1
 Lindsey Lakes has alias View Lake
 Crooked Lakes has alias Shotgun Lake
 Crooked Lakes has alias Lilyput Pond
renaming Crooked Lakes to Crooked Lake, Upper
 Five Lakes Basin has alias Blacks Lake
 Five Lakes Basin has alias Helen Lake
renaming Crooked Lakes to Crooked Lake, Middle
set empty name to Mont Lake
set empty name to Barbara Lake
set empty name to Eastern Brook Lake, Upper
renaming Beyers Lakes to Beyers Lake, Upper
 West Lakes has alias Maria Lake
set empty name to West Lake, Lower
 Lake Aloha has alias Aloha Lake
 Lower Kinney Lake has alias Kinney Lake, Lower
renaming Highland Lakes to Highland Lakes 1
renaming Highland Lakes to Highland Lakes 2
renaming Lewis Lakes to Lewis Lake, Upper
 Karls Lake has alias Karl's Lake
renaming Barney Lake to Barney Lake (E. Walker)
 Pruitt Lake has alias Pruitte Lake
renaming Par Value Lakes to Par Value Lake, Lower (2)
renaming Hoover Lakes to Hoover Lake, Lower
renaming Hoover Lakes to Hoover Lake, Upper
renaming Blue Lake to Blue Lake (E. Walker)
renaming Frog Lakes to Frog Lake, Middle
renaming Frog Lakes to Frog Lake, Lower
renaming Frog Lakes to Frog Lake, Upper
renaming Lake Helen to Helen Lake (Mono Lk)
renaming Steelhead Lake to Steelhead Lake (Mono)
renaming Green Lake to Green Lake (Mono Lk)
renaming Big Horn Lake to Bighorn Lake (Slate Creek)
set empty name to GNIS name:  Willow Lake
renaming Dana Lake to Dana Lake 4
 Lower Sardine Lake has alias Sardine Lake, Lower
 Upper Sardine Lake has alias Sardine Lake, Upper
renaming Alger Lakes to Alger Lake 3
renaming Alger Lakes to Alger Lake 1
renaming Lost Lakes to Lost Lake 3
set empty name to GNIS name:  Oakwood Lake
renaming Blue Jay Lakes to Blue Jay Lake 2
renaming Graveyard Lakes to Graveyard Lake, Lower
renaming Trail Lakes to Trail Lake
renaming Upper Horton Lakes to Horton Lake 3
set empty name to Three Quarter Lake
renaming Pinto Lakes to Pinto Lake
 Starr Jordan Lake has alias Starr Jordon Lake
renaming Fisher Lakes to Fisher Lakes 1
 Little Lake has alias Pass Lake
renaming Robinson Lakes to Robinson Lake, Upper
renaming Robinson Lakes to Robinson Lake, Lower
 Woods Lakes has alias Wood Lake, Upper
renaming Barney Lake to Barney Lake (Owens)
renaming Deer Lakes to Deer Lake 2
renaming Treasure Lakes to Treasure Lake 4 (Rock Ck)
renaming Treasure Lakes to Treasure Lake 1 (Rock Ck)
 Dunderberg Lake has alias Dunderburg Lake
renaming Beck Lakes to Beck Lake, Upper
renaming Ward Lakes to Ward Lake, Upper
renaming Ward Lakes to Ward Lake, Lower
renaming Nydiver Lakes to Nydiver Lake, Upper
renaming Laurel Lakes to Laurel Lake 1
renaming Gable Lakes to Gable Lake 1
renaming Gable Lakes to Gable Lake 3
renaming Post Lakes to Post Lakes 2
renaming Post Lakes to Post Lakes 1
 Neelle Lake has alias Needle Lake
renaming Summit Lake to Summit Lake (Mono Ck)
renaming Gable Lakes to Gable Lake 4
renaming Royce Lakes to Royce Lake 3
 Lower Turret Lake has alias Turret Lake, Lower
 Lakecamp Lake has alias Lake Camp Lake
renaming Blue Lake to Blue Lake (Mono Lake)
 Steelhead Lake, Little has alias Little Steelhead Lake
renaming Lost Lakes to Lost Lake 1
renaming Marie Lakes to Marie Lake, Upper
renaming Summit Lake to Agnew Pass Lake (Summit Lk)
renaming Davis Lakes to Davis Lake, Lower
renaming Badger Lakes to Badger Lake
renaming Davis Lakes to Davis Lake, Upper
renaming Isberg Lakes to Isberg Lake, Lower
renaming Beck Lakes to Beck Lake, Lower
renaming Slab Lakes to Slab Lakes 1
renaming Slab Lakes to Slab Lakes 5
renaming Sherwin Lakes to Sherwin Lake 3
 McLeod Lake has alias McCleod Lake
renaming Cora Lakes to Cora Lake, Middle
 T J Lake has alias Tee Jay Lake
renaming Fernandez Lakes to Fernandez Lake, Lower
renaming Laurel Lakes to Laurel Lake 2
renaming Deer Lakes to Deer Lake 3
renaming Deer Lakes to Deer Lake 3
 Stanford Lakes has alias Staniford Lake, Lower
renaming Lady Lake to Lady Lake (Madera, Middle)
renaming Franklin Lake to Franklin Lake 3
renaming Bighorn Lake to Bighorn Lake (Owens)
renaming Jackass Lakes to Jackass Lake, Upper
 Lake Wit-so-nah-pah has alias Wit-So-Nah-Pah Lake
renaming Lost Keys Lakes to Lost Keys Lake 3
renaming Lost Keys Lakes to Lost Keys Lake (Bench, lower or west)
renaming Lost Keys Lakes to Lost Keys Lake, East
renaming Star Lakes to Star Lake, Lower
renaming Bench Lakes to Bench Lake 4
renaming Bench Lakes to Bench Lake 1
renaming Steelhead Lake to Steelhead Lake (McGee Ck)
renaming Bench Lakes to Bench Lake 3
 Golden Lake has alias Golden (Gold) Lake
 Little McGee Lake has alias McGee Lake, Upper
renaming Hilton Creek Lakes to Hilton Lake 3
renaming Pioneer Basin Lakes to Pioneer Lake 6
renaming Hilton Creek Lakes to Hilton Lake 4
renaming Pioneer Basin Lakes to Pioneer Lake 5
renaming Hilton Creek Lakes to Hilton Lake 5
renaming Shorty Lake to Shorty Lake (Margaret)
renaming Pioneer Basin Lakes to Pioneer Lake 4
renaming Sedge Lake to Sedge Lake (Margaret)
renaming Peter Pande Lake to Peter Pande Lake (Marilyn)
 Wilbur May Lake has alias Wilber May Lake
 Pioneer Basin Lakes has alias Pioneer Lake 2A
renaming Pioneer Basin Lakes to Pioneer Lake 2
 Lower Hopkins Lake has alias Hopkins Lake, Lower
renaming Frog Lake to Frog Lake (Margaret)
renaming Fern Lake to Fern Lake (Margaret)
renaming Graveyard Lakes to Graveyard Lake, Upper
 Graveyard Lakes has alias Ghost Lake
renaming Heart Lake to Heart Lake (Rock Ck)
renaming Snow Lakes to Snow Lake, Lower
renaming Hidden Lakes to Hidden Lake 3
renaming Hidden Lakes to Lost Lake (Rock Ck)
renaming Snow Lakes to Snow Lake, Upper
renaming Long Lake to Long Lake (Rock Ck)
renaming Gem Lakes to Gem Lake, Lower
 Upper Mills Creek Lake has alias Mills Creek Lake, Upper
renaming Gem Lakes to Gem Lake, Upper
 Upper Morgan Lake has alias Morgan Lake, Upper
renaming Treasure Lakes to Treasure Lake 2 (Rock Ck)
 Lower Morgan Lake has alias Morgan Lake, Lower
renaming Bear Twin Lakes to Bear Twin Lake, East
renaming Bear Twin Lakes to Bear Twin Lake, West
renaming Upper Chalfant Lake to Chalfant Lakes 9
renaming Granite Park 3 to Granite Park Lake 3
 Teddy Bear Lake has alias Teddybear Lake
renaming Granite Park 2 to Granite Park Lake 2
renaming Tule Lake to Tule Lake (Trib to Mono Cr.)
renaming Granite Park 1 to Granite Park Lake 1
renaming Golden Lake to Golden Lake (Large)
renaming Longley Lake to Longley Reservoir (McGee Lake)
renaming Horton Lake to Horton Lake 2
renaming Royce Lakes to Royce Lake 2
renaming Pryor Lake to Pryor Lake (not Prior Lake)
 Flat Note Lake has alias Flatnote Lake
 Sharp Note Lake has alias Sharpnote Lake
 Little Moccasin Lake has alias Moccasin Lake, Little
renaming Humphreys Lakes to Humphreys Lake, Lower
renaming Humphreys Lakes to Humphreys Lake, Upper
 Lower Honeymoon Lake has alias Honeymoon Lake, Lower
renaming Hidden Lake to Hidden Lake (Trib. to Florence Lk.)
renaming Summit Lake to Summit Lake (Piute Ck)
renaming Lost Lakes to Lost Lake 1
renaming Lost Lakes to Lost Lake 4
renaming Wonder Lakes to Wonder Lake 3
 Lower Lamarck Lake has alias Lamarck Lake, Lower
 Upper Lamarck Lake has alias Lamarck Lake, Upper
renaming Fishgut Lakes to Fishgut Lake 2
set empty name to Post Corral Lake 4
renaming Schober Holes to Schober Hole 1
renaming Emerald Lakes to Emerald Lake 1
renaming Schober Holes to Schober Hole 3
renaming Tyee Lakes to Tyee Lake 5
renaming Hell Diver Lakes to Hell Diver Lake 1
renaming Hell Diver Lakes to Hell Diver Lake 2
renaming Hell Diver Lakes to Hell Diver Lake 3
renaming Turf Lakes to Turf Lake, Lower
renaming Sailor Lake to Drunken Sailor Lake
 Lower Indian Lake has alias Indian Lake, Lower
renaming Hidden Lake to Hidden Lake (Baker Ck)
renaming Sunset Lake to Sunset Lake (Baboon Lake 4)
 Second Dinkey Lake has alias Dinkey Lake, Second
renaming Rainbow Lake to Rainbow Lake (Dinkey)
renaming Treasure Lakes to Treasure Lake 5 (Bishop Ck)
renaming Cliff Lake to Cliff Lake (Helms)
renaming Sixth Lake to Big Pine Lake 6
renaming Summit Lake to Summit Lake (Swift Lk)
renaming First Lake to Big Pine Lake 1
 Little Doris Lake has alias Doris Lake, Little
renaming Lost Lakes to Lost Lake 2
renaming Clark Lakes to Clark Lake 2
renaming Clark Lakes to Clark Lake 4
set empty name to Bench Canyon Lake
renaming Jackass Lakes to Jackass Lake, Lower
renaming Jackass Lakes to Jackass Lake, Middle
renaming Hidden Lake to Hidden Lake (Morgan Ck)
renaming Sherwin Lakes to Sherwin Lake 1
renaming Sherwin Lakes to Sherwin Lake 2
renaming Cora Lakes to Cora Lake, Lower
renaming Stanford Lakes to Stanford Lakes 5
set empty name to Madera Lake, Upper
renaming Hilton Creek Lakes to Hilton Lake 6
renaming Hilton Creek Lakes to Hilton Lake 8
renaming Hilton Creek Lakes to Hilton Lake 7
 Pioneer Basin Lakes has alias Pioneer Lake 1A
set empty name to Unnamed Lake (E Fk Rock Ck (1st one))
 Graveyard Lakes has alias Phantom Lake
 Graveyard Lakes has alias Vengeance Lake
renaming Blue Jay Lakes to Blue Jay Lake 1
renaming Hidden Lakes to Hidden Lake 5
 Little Lakes has alias Little Fish Lake
renaming Little Lakes to Big Fish Lake 3
 Lower Chalfant Lake has alias Chalfant Lake, Lower
renaming Seven Gables Lakes to Seven Gables Lake 7
renaming Seven Gables Lakes to Seven Gables Lake 6
renaming Upper Horton Lakes to Horton Lake 4
 Golden Trout No. 2 has alias Golden Trout Lake 2
renaming Geraldine Lakes to Geraldine Lake, Upper
renaming Lower Twin Lake to Twin Lake, Lower (White Cliff)
renaming Lost Lakes to Lost Lake 2
renaming Taboose to Taboose Lake
 Chain Lakes has alias Rancheria Lake
renaming Fishgut Lakes to Fishgut Lake 1
renaming Wonder Lakes to Wonder Lake 2
renaming Tyee Lakes to Tyee Lake 1
renaming Tyee Lakes to Tyee Lake 2
renaming Tyee Lakes to Tyee Lake 3
renaming Emerald Lakes to Emerald Lake 3
set empty name to Post Corral Lake 5
renaming Tyee Lakes to Tyee Lake 6
 Pee Wee Lake has alias Pee-Wee Lake
set empty name to Post Corral Lake 2
renaming Chain Lakes to Chain Lake, Upper
renaming Baboon Lakes to Baboon Lake, Upper
renaming Treasure Lakes to Treasure Lake 2 (BishopCk)
renaming Treasure Lakes to Treasure Lake 3 (Bishop Ck)
renaming Treasure Lakes to Treasure Lake 4 (Bishop Ck)
renaming Treasure Lakes to Treasure Lake 6 (Bishop Ck)
renaming Parker Lakes to Oak Creek Lake 2 (Parker Lake, Upper)
renaming Jigger Lakes to Jigger Lake, Short
 Big Shot Lake has alias Shot Lake, Big
renaming Mud Lakes to Mud Lake, Lower
renaming Mud Lakes to Mud Lake, Upper
renaming Twin Buck Lakes to Twin Buck Lake, East
renaming Nelson Lakes to Nelson Lake, Upper
renaming Twin Buck Lakes to Twin Buck Lake, West
 Sportsman Lake has alias Sportsmen Lake
renaming McGuire Lakes to McGuire Lakes 2
renaming McGuire Lakes to McGuire Lakes 1
 Red Lake has alias Red Mountain Lake
renaming Spanish Lake to Spanish Lake, Big
 Little Spanish Lake has alias Spanish Lake, Little
renaming Twin Lakes to Twin Lake, Long
renaming Twin Lakes to Twin Lake, Round
renaming Geraldine Lakes to Geraldine Lake, Lower
renaming Parker Lakes to Oak Creek Lake 1 (Parker Lake, Lower)
renaming Golden Trout Lake to Golden Trout Lake 4
 Big Pothole Lake has alias Big Pot Hole Lake
 Little Pothole Lake has alias Pothole Lake, Little
renaming Heart Lake to Heart Lake (Independence Ck)
renaming Robinson Lake to Robinson Lake (Grace Lake)
 Williamson No. 2 has alias Williamson Lake 2
 Williamson No. 3 has alias Williamson Lake 3
 Upper Boy Scout Lake has alias Boy Scout Lake, Upper
renaming Meysan Lake to Meysan Lake, Upper
renaming Cottonwood Lakes to Cottonwood Lake 5
renaming Cottonwood Lakes to Cottonwood Lake 4
renaming Cottonwood Lakes to Cottonwood Lake 3
renaming Long Lake to Long Lake (Cottonwood Ck)
renaming Bullfrog Lakes to Bullfrog Lake, Upper
 Six Shooter Lake has alias Sixshooter Lake
set empty name to Chain Lakes, Middle
set empty name to GNIS name:  Ski Land Lake
set empty name to GNIS name:  Santiago Creek Recharge Basin
 Roman Four Lake has alias Roman Lake
set empty name to GNIS name:  Palo Verde Lake
 Round Lake has alias Round Meadow
set empty name to Inspiration Lake
set empty name to Wee Bear
set empty name to McGee Lake, Little
 Little Kern Lake has alias Kern Lake, Little
set empty name to GNIS name:  Fairview Dry Lake
set empty name to GNIS name:  Hansen Flood Control Basin
set empty name to GNIS name:  Upper Oso Reservoir
set empty name to GNIS name:  Papoose Lake
set empty name to GNIS name:  Quarry Lake
 Feely Lake has alias Feeley Lake
set empty name to Island Lake, Little
 Lock Leven Lakes (upper) has alias Loch Leven, Upper
set empty name to Unnamed 1 (near Fontanillis)
set empty name to Unnamed 2 (near Fontanillis)
set empty name to North Fork Stanislaus River Diversion Dam.
 Kelley Lake has alias Kelly Lake
 Cuddihy Lakes 1 has alias Cuddihy Lake 1
 Cuddihy Lakes 3 has alias Cuddihy Lake 3
 Mill Creek Ponds has alias Mill Creek Lake, Lower
renaming Hancock Lake to Hancock Lake, Big
renaming English Lake to English Lake, Lower
renaming Crater Lake to Crater Lake, Big (China Mountain)
renaming Eaton Lakes to Eaton Lakes, North
renaming Deadfall Lakes, Lower to Deadfall Lake, Lower (Trinity Divide)
 Big Duck Lake has alias Duck Lake, Big
renaming Deadfall Lakes, Upper to Deadfall Lake, Middle (Trinity Divide)
renaming Russian Lake to Russian Lake, Upper
 Washbasin Lake has alias Washbasin lake
renaming Tangle Blue Lake to Tangle Blue Lake (Salmon Scott)
renaming Gumboot Lake to Gumboot Lake, Lower
 South Fork Lakes 2 has alias South Forks Lakes 2
 Big Bear Lake has alias Bear Lake, Big
renaming Mumbo Lake to Mumbo Lake, Lower (Trinity Divide)
renaming Stoddard Lake to Stoddard Lake Lower, Salmon Scott
renaming McDonald Lake to McDonald Lake (Salmon Scott)
 Twin Lakes 1 has alias Twin Lake, Lower, Trinity Divide
renaming Tamarack Lake to Tamarack Lake, Lower (Trinity Divide)
 Twin Lakes 2 has alias Twin Lake, Upper, Trinity Divide
renaming Highland Lake to Highland Lake (Trinity Divide)
renaming Sugar Pine Lake to Sugar Pine Lake, Trinity Alps

In [7]:
from geoalchemy2.shape import from_shape

# table_data["nominal_coords"] = table_data["nominal_coords"].apply(
#     lambda geom: from_shape(geom, srid=4326) if geom else None
# )

In [8]:
print(type(table_data))
print("geometry column:", table_data.geometry.name)
print("active geometry:", table_data._geometry_column_name)
print("is geodataframe:", hasattr(table_data, "geometry"))

<class 'geopandas.geodataframe.GeoDataFrame'>
geometry column: boundary
active geometry: boundary
is geodataframe: True

In [9]:
print(type(table_data["nominal_coords"].iloc[0]))

<class 'shapely.geometry.point.Point'>

In [10]:
import logging
import os
logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.DEBUG)
# --- database connection ---
db_user = os.environ.get("TERA_DB_USR")
db_pswrd = os.environ.get("TERA_DB_PSWRD")
engine = create_engine(f"postgresql+psycopg2://{db_user}:{db_pswrd}@localhost/tera")

with engine.connect() as con:
    print("Connected!")

INFO:sqlalchemy.engine.Engine:select pg_catalog.version()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('version',)
DEBUG:sqlalchemy.engine.Engine:Row ('PostgreSQL 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit',)
INFO:sqlalchemy.engine.Engine:select current_schema()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('current_schema',)
DEBUG:sqlalchemy.engine.Engine:Row ('public',)
INFO:sqlalchemy.engine.Engine:show standard_conforming_strings
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('standard_conforming_strings',)
DEBUG:sqlalchemy.engine.Engine:Row ('on',)

Connected!

In [11]:
# upload to PostGIS

try:
    table_data.to_postgis(
        name="water_bodies",
        con=engine,
        if_exists="append",
        index=False,
        dtype={
            "boundary": Geometry("MULTIPOLYGON", srid=4326),
            "nominal_coords": Geometry("POINT", srid=4326)
        }
    )
except Exception as e:
    import traceback
    traceback.print_exc()

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[generated in 0.00089s] {'table_name': 'water_bodies', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[generated in 0.00086s] {'table_name': 'water_bodies', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'public'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
INFO:sqlalchemy.engine.Engine:
CREATE TABLE public.water_bodies (
	name TEXT,
	boundary geometry(MULTIPOLYGONZ,4326),
	nominal_coords geometry(POINT,4326),
	elevation INTEGER,
	surface_area FLOAT(53),
	state TEXT,
	county TEXT,
	state_id INTEGER,
	gnis_id INTEGER
)


INFO:sqlalchemy.engine.Engine:[no key 0.00080s] {}
INFO:sqlalchemy.engine.Engine:CREATE INDEX idx_water_bodies_nominal_coords ON public.water_bodies USING gist (nominal_coords)
INFO:sqlalchemy.engine.Engine:[no key 0.00088s] {}
INFO:sqlalchemy.engine.Engine:CREATE INDEX idx_water_bodies_boundary ON public.water_bodies USING gist (boundary)
INFO:sqlalchemy.engine.Engine:[no key 0.00073s] {}
INFO:sqlalchemy.engine.Engine:COMMIT

In [12]:
table_data

,name,boundary,nominal_coords,elevation,surface_area,state,county,state_id,gnis_id
0,,"MULTIPOLYGON Z (((-122.6329 41.99307 0, -122.6...",POINT (-122.63469 41.99551),2832,12.647377,CA,Siskiyou,2,0
1,Azalea Lake,"MULTIPOLYGON Z (((-123.30004 41.96928 0, -123....",POINT (-123.30053 41.96988),5383,4.601394,CA,Siskiyou,5,256390
2,White Lake,"MULTIPOLYGON Z (((-121.64563 41.99942 0, -121....",POINT (-121.63324 41.99478),4093,814.471819,CA,Siskiyou,9,269006
3,Bear Wallow,"MULTIPOLYGON Z (((-123.65463 41.95017 0, -123....",POINT (-123.65479 41.95033),4380,0.292219,CA,Del Norte,35,256730
4,Mud Lake,"MULTIPOLYGON Z (((-121.98281 41.98446 0, -121....",POINT (-121.98372 41.98555),4763,11.463147,CA,Siskiyou,39,1657412
...,...,...,...,...,...,...,...,...,...
27501,,"MULTIPOLYGON Z (((-115.46938 32.99405 0, -115....",POINT (-115.46978 32.99283),-147,15.538655,CA,Imperial,7792,0
27502,Clover Creek Pond,"MULTIPOLYGON Z (((-122.31356 40.55139 0, -122....",POINT (-122.31361 40.55054),500,9.408521,CA,Shasta,28569,0
27503,Battle Creek Pond,"MULTIPOLYGON Z (((-122.17572 40.38907 0, -122....",POINT (-122.17561 40.38861),430,3.393287,CA,Tehama,28568,0
27504,Sycamore Island Pond,"MULTIPOLYGON Z (((-119.82334 36.85213 0, -119....",POINT (-119.82595 36.85164),265,34.781933,CA,Madera,28570,0
27505,Libby Water,"MULTIPOLYGON Z (((-120.47625 38.1052 0, -120.4...",POINT (-120.47638 38.10502),2000,0.552185,CA,Calaveras,28572,0

In [13]:
missing = survey_data.loc[~survey_data['CaLakesID'].isin(table_data['state_id'])]
acres_per_hectare = 2.47105
missing_table_data = gpd.GeoDataFrame({
    #table values are as follows:
    #name
    "name": missing["LakeName"],
    #nominal_coords (todo: rename centroid to nominal_coords
    "nominal_coords": missing["geometry"],
    #surface_area
    "surface_area": missing["AreaHectares"]*acres_per_hectare,
    #state
    "state": "CA",
    #state_id
    "state_id": missing["CaLakesID"],
    
    }, geometry="nominal_coords", crs = gdf.crs )

missing_table_data= missing_table_data.drop_duplicates()

In [14]:
missing_table_data

,name,nominal_coords,surface_area,state,state_id
140,Lake Katherine,POINT (-123.21702 41.45322),5.411599,CA,333
648,Grouse Creek Lake,POINT (-119.71149 38.24764),4.942100,CA,3256
751,NaN,POINT (-121.35895 40.128),0.098842,CA,11738
1099,NaN,POINT (-120.55812 39.41173),0.494210,CA,12693
1488,NaN,POINT (-120.17055 38.87779),0.296526,CA,14142
...,...,...,...,...,...
4036,NaN,POINT (-120.48265 39.36831),0.988420,CA,52594
4037,"Mulkey Creek, Middle",POINT (-118.16059 36.40935),2.174524,CA,52634
4038,NaN,POINT (-118.80654 37.39625),0.395368,CA,52652
4039,Ball's Canyon Creek,POINT (-120.05319 39.6563),0.494210,CA,52653
4040,Last Chance Creek,POINT (-120.48563 40.11205),0.889578,CA,52654

In [15]:
try:
    missing_table_data.to_postgis(
        name="water_bodies",
        con=engine,
        if_exists="append",
        index=False,
        dtype={
            "nominal_coords": Geometry("POINT", srid=4326)
        }
    )
except Exception as e:
    import traceback
    traceback.print_exc()

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[cached since 16.38s ago] {'table_name': 'water_bodies', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
DEBUG:sqlalchemy.engine.Engine:Row ('water_bodies',)
INFO:sqlalchemy.engine.Engine:SELECT Find_SRID(%(schema_name)s, %(name)s, %(geom_name)s);
INFO:sqlalchemy.engine.Engine:[generated in 0.00263s] {'schema_name': 'public', 'name': 'water_bodies', 'geom_name': 'nominal_coords'}
DEBUG:sqlalchemy.engine.Engine:Col ('find_srid',)
DEBUG:sqlalchemy.engine.Engine:Row (4326,)
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[cached since 16.43s ago] {'table_name': 'water_bodies', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'public'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
DEBUG:sqlalchemy.engine.Engine:Row ('water_bodies',)
INFO:sqlalchemy.engine.Engine:COMMIT

In [ ]:
#then run this command to add the index column
ALTER TABLE water_bodies
ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY;


#then run
UPDATE water_bodies SET name = NULL WHERE name = ' ';