In [26]:
import geopandas as gpd
import pandas as pd
from sqlalchemy import create_engine
from geoalchemy2 import Geometry
from shapely.geometry import MultiPolygon

import logging

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.DEBUG)

In [16]:
survey_file_name = "Fish_-_High_Mountain_Lakes_[ds102].geojson"
survey_data = gpd.read_file(survey_file_name)

In [14]:
survey_data.columns

Index(['OBJECTID', 'ScientificName', 'SpeciesName', 'SurveyDate', 'SpeciesID',
       'FishCount', 'AveLength', 'MinLength', 'MaxLength', 'AveWeight',
       'MinWeight', 'MaxWeight', 'FishSurveyMethod', 'SurveyTypeDesc',
       'CaLakesID', 'LakeName', 'HML_ID', 'FishNotPresent', 'AreaHectares',
       'LatLong_X', 'LatLong_Y', 'geometry'],
      dtype='str')

In [19]:
inches_per_mm = 0.03937
survey_table_data = gpd.GeoDataFrame({
    "species": survey_data["SpeciesID"],
    "date": survey_data["SurveyDate"],
    "count": survey_data["FishCount"],
    "length_avg": survey_data["AveLength"]*inches_per_mm,# conver mm to inches
    "length_min": survey_data["MinLength"]*inches_per_mm,
    "length_max": survey_data["MaxLength"]*inches_per_mm,
    "type": "CDFW survey",
    "method": survey_data["FishSurveyMethod"],
    "CALakeID": survey_data["CaLakesID"],
    "coords": survey_data["geometry"],
    "source": survey_file_name
}, geometry="coords", crs = gdf.crs)

survey_table_data

,species,date,count,length_avg,length_min,length_max,type,method,CALakeID,coords,source
0,BK,2002-08-07,19,7.900937,6.45668,9.80313,CDFW survey,gill net,5,POINT (-123.30053 41.96988),Fish_-_High_Mountain_Lakes_[ds102].geojson
1,BK,2002-08-08,17,8.253805,3.34645,12.59840,CDFW survey,gill net,58,POINT (-123.29779 41.94959),Fish_-_High_Mountain_Lakes_[ds102].geojson
2,BK,2002-06-28,5,12.724384,12.08659,13.46454,CDFW survey,gill net,80,POINT (-123.17324 41.9363),Fish_-_High_Mountain_Lakes_[ds102].geojson
3,BK,2002-06-27,1,7.598410,7.59841,7.59841,CDFW survey,gill net,82,POINT (-123.19785 41.93446),Fish_-_High_Mountain_Lakes_[ds102].geojson
4,RT,2002-06-18,13,9.082356,8.26770,10.11809,CDFW survey,gill net,92,POINT (-123.51729 41.9132),Fish_-_High_Mountain_Lakes_[ds102].geojson
...,...,...,...,...,...,...,...,...,...,...,...
4041,DC,2013-06-18,35,2.178473,1.53543,3.11023,CDFW survey,electrofish,52654,POINT (-120.48563 40.11205),Fish_-_High_Mountain_Lakes_[ds102].geojson
4042,RT,2013-06-18,3,6.089227,4.84251,7.28345,CDFW survey,electrofish,52654,POINT (-120.48563 40.11205),Fish_-_High_Mountain_Lakes_[ds102].geojson
4043,SKR-T,2013-06-18,2,5.059045,3.97637,6.14172,CDFW survey,electrofish,52654,POINT (-120.48563 40.11205),Fish_-_High_Mountain_Lakes_[ds102].geojson
4044,TRT,2012-08-17,1,NaN,NaN,NaN,CDFW survey,visual,66159,POINT (-120.16993 38.87762),Fish_-_High_Mountain_Lakes_[ds102].geojson
4045,TRT,2010-08-19,1,7.992110,7.99211,7.99211,CDFW survey,visual,66159,POINT (-120.16993 38.87762),Fish_-_High_Mountain_Lakes_[ds102].geojson

In [25]:
survey_table_data[survey_table_data["CALakeID"]== None]

Empty GeoDataFrame
Columns: [species, date, count, length_avg, length_min, length_max, type, method, CALakeID, coords, source]
Index: []

In [27]:
# planting_file_name = "Planting_Location_-_CDFW_[ds2897].geojson"
# planting_data = gpd.read_file(planting_file_name)

<class 'geoalchemy2.elements.WKBElement'>

In [28]:
import os
# --- database connection ---
db_user = os.environ.get("TERA_DB_USR")
db_pswrd = os.environ.get("TERA_DB_PSWRD")
engine = create_engine(f"postgresql+psycopg2://{db_user}:{db_pswrd}@localhost/tera")

with engine.connect() as con:
    print("Connected!")

INFO:sqlalchemy.engine.Engine:select pg_catalog.version()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('version',)
DEBUG:sqlalchemy.engine.Engine:Row ('PostgreSQL 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit',)
INFO:sqlalchemy.engine.Engine:select current_schema()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('current_schema',)
DEBUG:sqlalchemy.engine.Engine:Row ('public',)
INFO:sqlalchemy.engine.Engine:show standard_conforming_strings
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('standard_conforming_strings',)
DEBUG:sqlalchemy.engine.Engine:Row ('on',)

Connected!

In [30]:
# upload to PostGIS

try:
    survey_table_data.to_postgis(
        name="cdfw_surveys",
        con=engine,
        if_exists="append",
        index=False,
        dtype={
            "coords": Geometry("POINT", srid=4326)
        }
    )
except Exception as e:
    import traceback
    traceback.print_exc()

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[cached since 271.1s ago] {'table_name': 'cdfw_surveys', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[cached since 271.1s ago] {'table_name': 'cdfw_surveys', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'public'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
INFO:sqlalchemy.engine.Engine:
CREATE TABLE public.cdfw_surveys (
	species TEXT,
	date TIMESTAMP WITHOUT TIME ZONE,
	count INTEGER,
	length_avg FLOAT(53),
	length_min FLOAT(53),
	length_max FLOAT(53),
	type TEXT,
	method TEXT,
	"CALakeID" INTEGER,
	coords geometry(POINT,4326),
	source TEXT
)


INFO:sqlalchemy.engine.Engine:[no key 0.00245s] {}
INFO:sqlalchemy.engine.Engine:CREATE INDEX idx_cdfw_surveys_coords ON public.cdfw_surveys USING gist (coords)
INFO:sqlalchemy.engine.Engine:[no key 0.00236s] {}
INFO:sqlalchemy.engine.Engine:COMMIT

In [33]:
survey_table_data[survey_table_data["CALakeID"]==""]

Empty GeoDataFrame
Columns: [species, date, count, length_avg, length_min, length_max, type, method, CALakeID, coords, source]
Index: []