In [3]:
import geopandas as gpd
import pandas as pd
import fiona
from sqlalchemy import create_engine
from geoalchemy2 import Geometry
from shapely.geometry import MultiPolygon, shape, mapping


#update the names of the lakes if we have a beter option
import sys
sys.path.insert(0, "/home/whurst/dev/water_weather_apis/")
from nationalmap import NationalMap as NatMap
import requests
NatMap.set_requester(requests)
import time

In [5]:
# Enable KML driver support
fiona.drvsupport.supported_drivers['KML'] = 'rw' 

# Read the KML file
winds_routes = gpd.read_file('Routes.kml', driver='KML')
winds_routes

,id,Name,description,timestamp,begin,end,altitudeMode,tessellate,extrude,visibility,drawOrder,icon,Primary_Trail,Other_Trails,Distance,Type,Trails,geometry
0,None,Elkhart Park to Pine Creek & Upper Fremont Lak...,,NaT,NaT,NaT,None,1,0,-1,NaN,None,faller Creek,,2,,,"LINESTRING Z (-109.7525 43.00617 0, -109.75395..."
1,None,Lake 11125 - Denis Lake outlet,descent down to Denis is very steep\n,NaT,NaT,NaT,None,1,0,-1,NaN,None,angel pass (ot),,1.25,,,"LINESTRING Z (-109.5091 43.02035 0, -109.5132 ..."
2,None,Eklund - Pole Creek Lakes,"3.3 miles, 2.1 hours (down). Pole Creek Trail",NaT,NaT,NaT,None,1,0,-1,NaN,None,pole creek,,3.3,,,"LINESTRING Z (-109.62722 43.01098 0, -109.6300..."
3,None,"Pole Creek Lakes - Cook Lakes turnoff, South\n","1.3 miles, to frmnt junction 1.2 hours (up). H...",NaT,NaT,NaT,None,1,0,-1,NaN,None,highline,,1\n,,,"LINESTRING Z (-109.60918 43.0207 0, -109.60929..."
4,None,Fremont Trail Junction - Bald Mountain Basin,"1.2 miles, 0.9 hours (up) Fremont Trail",NaT,NaT,NaT,None,1,0,-1,NaN,None,fremont,,1.2,,,"LINESTRING Z (-109.58902 43.01555 0, -109.5922..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,None,Lake 10834 to Bloody Hell Pass\n,"NP route, rated R\n",NaT,NaT,NaT,None,1,0,-1,NaN,None,shangri-la,,1.1,off trail\n,,"LINESTRING Z (-109.54133 43.13025 0, -109.5390..."
192,None,Bloody Hell Pass to Lake 10980 Inlet\n,"NP route, rated R\n",NaT,NaT,NaT,None,1,0,-1,NaN,None,shangri-la,,0.7,off trail\n,,"LINESTRING Z (-109.53432 43.10875 0, -109.5360..."
193,None,Lake 10980 inlet to Rich Lake #2\n,"NP route, rated G\n",NaT,NaT,NaT,None,1,0,-1,NaN,None,shangri-la,,1.7,off trail\n,,"LINESTRING Z (-109.53387 43.09839 0, -109.5317..."
194,None,Meadow to Bridge\n,,NaT,NaT,NaT,None,1,0,-1,NaN,None,Bob Creek\n,,,,,"LINESTRING Z (-109.48521 43.2451 0, -109.48515..."
195,None,Cub - Norman\n,,NaT,NaT,NaT,None,1,0,-1,NaN,None,dry creek\n,,,,,"LINESTRING Z (-109.53974 43.20988 0, -109.5388..."

In [14]:
winds_routes["Type"].fillna("").str.replace(r"\s+", "", regex=True)

0
1
2
3
4
         ...
191    offtrail
192    offtrail
193    offtrail
194
195
Name: Type, Length: 196, dtype: str

In [15]:
table_data = gpd.GeoDataFrame({
    "name": winds_routes["Name"],
    "route_name": winds_routes["Primary_Trail"],
    "description": winds_routes["description"],
    "is_off_trail": (winds_routes["Type"]
                    .fillna("")
                    .str.replace(r"\s+", "", regex=True)
                    .eq("offtrail")
                    ),
    "geometry": winds_routes["geometry"]
})

table_data

,name,route_name,description,is_off_trail
0,Elkhart Park to Pine Creek & Upper Fremont Lak...,faller Creek,,False
1,Lake 11125 - Denis Lake outlet,angel pass (ot),descent down to Denis is very steep\n,False
2,Eklund - Pole Creek Lakes,pole creek,"3.3 miles, 2.1 hours (down). Pole Creek Trail",False
3,"Pole Creek Lakes - Cook Lakes turnoff, South\n",highline,"1.3 miles, to frmnt junction 1.2 hours (up). H...",False
4,Fremont Trail Junction - Bald Mountain Basin,fremont,"1.2 miles, 0.9 hours (up) Fremont Trail",False
...,...,...,...,...
191,Lake 10834 to Bloody Hell Pass\n,shangri-la,"NP route, rated R\n",True
192,Bloody Hell Pass to Lake 10980 Inlet\n,shangri-la,"NP route, rated R\n",True
193,Lake 10980 inlet to Rich Lake #2\n,shangri-la,"NP route, rated G\n",True
194,Meadow to Bridge\n,Bob Creek\n,,False
195,Cub - Norman\n,dry creek\n,,False

In [39]:

wyoming_transportation_gdb = "TRAN_Wyoming_State_GDB/TRAN_Wyoming_State_GDB.gdb"
# Rough bounding box for Wind River Range
layers = fiona.listlayers(wyoming_transportation_gdb)
print(layers)

gdf = gpd.read_file(wyoming_transportation_gdb, layer='Trans_TrailSegment')
winds = gdf.cx[-110.9:-108.5, 42.5:44.2]
winds_hiking = winds[winds["hikerpedestrian"]=="Y"]

print(winds.columns)

winds_hiking = winds_hiking[["name", "trailnumber", "lengthmiles", "sourceoriginator", "permanentidentifier", "geometry"]]
print(len(winds_hiking))
winds_hiking.head()

['BPFeatureToMetadata', 'Meta_DatasetDetail', 'Meta_ProcessDetail', 'CLIPPOLY', 'Trans_TrailSegment', 'Trans_RoadSegment', 'Trans_RailFeature', 'Trans_AirportRunway', 'Trans_AirportPoint']

/home/whurst/dev/tera/.tera/lib/python3.12/site-packages/pyogrio/raw.py:200: UserWarning: Measured (M) geometry types are not supported. Original type 'Measured MultiLineString' is converted to 'MultiLineString'
  return ogr_read(

Index(['bicycle', 'crosscountryski', 'dogsled', 'ebike', 'electricwatercraft',
       'GLOBALID', 'hikerpedestrian', 'icewatercraft', 'lengthmiles',
       'livestock', 'loaddate', 'maplabel', 'motorcycle', 'name',
       'namealternate', 'nationaltraildesignation', 'networklength',
       'nonmotorizedwatercraft', 'ohvisorunder50inches', 'ohvover50inches',
       'OSVm', 'packsaddle', 'permanentidentifier', 'pets',
       'primarytrailmaintainer', 'publisheddate', 'routetype', 'seasonopen',
       'snowshoe', 'sourcedatadecscription', 'sourcedatasetid',
       'sourceeditdate', 'sourcefeatureid', 'sourceoriginator', 'trailnumber',
       'trailnumberalternate', 'trailsurface', 'trailtype', 'SHAPE_Length',
       'geometry'],
      dtype='str')
1346

,name,trailnumber,lengthmiles,sourceoriginator,permanentidentifier,geometry
165,Miller Butte Trail,T300,0.559478,U.S. Fish and Wildlife Service,53721458-2e0c-47e2-bcfb-2607b7810abd,"MULTILINESTRING ((-110.72123 43.50411, -110.72..."
168,Dry Hollow Trail,T301,0.978652,U.S. Fish and Wildlife Service,5e49e69e-f4a6-42e1-a301-f08f93446fa6,"MULTILINESTRING ((-110.62601 43.55855, -110.62..."
484,Continental Divide National Scenic Trail,6047,1.607828,U.S. Forest Service,0c0e71ac-8601-4f9f-baa0-05f32ba925dc,"MULTILINESTRING ((-110.20906 43.91754, -110.20..."
488,Trapper Lake,7168,4.535536,U.S. Forest Service,eb5a2a92-9bc9-412e-8c56-d9d09e3f0578,"MULTILINESTRING ((-109.78463 43.08111, -109.78..."
490,Continental Divide National Scenic Trail,7999A,2.657433,U.S. Forest Service,993a8aed-dd77-4db8-b10d-dea78a947cf2,"MULTILINESTRING ((-109.05726 42.56322, -109.05..."

In [38]:
winds_hiking[winds_hiking["name"]=="Continental Divide National Scenic Trail"]["lengthmiles"].sum()

np.float64(211.01381053)

In [45]:
table_data = gpd.GeoDataFrame({
    "name": winds_hiking["name"],
    "trail_number": winds_hiking["trailnumber"],
    "length": winds_hiking["lengthmiles"],
    "owner": winds_hiking["sourceoriginator"],
    "state": "WY",
    "source": wyoming_transportation_gdb,
    "id_in_source": winds_hiking["permanentidentifier"],
    "geometry": winds_hiking["geometry"]
})

In [44]:
import logging
import os

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.DEBUG)
# --- database connection ---
db_user = os.environ.get("TERA_DB_USR")
db_pswrd = os.environ.get("TERA_DB_PSWRD")
engine = create_engine(f"postgresql+psycopg2://{db_user}:{db_pswrd}@localhost/tera")

with engine.connect() as con:
    print("Connected!")

INFO:sqlalchemy.engine.Engine:select pg_catalog.version()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('version',)
DEBUG:sqlalchemy.engine.Engine:Row ('PostgreSQL 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit',)
INFO:sqlalchemy.engine.Engine:select current_schema()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('current_schema',)
DEBUG:sqlalchemy.engine.Engine:Row ('public',)
INFO:sqlalchemy.engine.Engine:show standard_conforming_strings
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('standard_conforming_strings',)
DEBUG:sqlalchemy.engine.Engine:Row ('on',)

Connected!

In [46]:
# upload to PostGIS

try:
    table_data.to_postgis(
        name="trails",
        con=engine,
        if_exists="append",
        index=False
    )
except Exception as e:
    import traceback
    traceback.print_exc()

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[generated in 0.00051s] {'table_name': 'trails', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[generated in 0.00073s] {'table_name': 'trails', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'public'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
INFO:sqlalchemy.engine.Engine:
CREATE TABLE public.trails (
	name TEXT,
	trail_number TEXT,
	length FLOAT(53),
	owner TEXT,
	state TEXT,
	source TEXT,
	id_in_source TEXT,
	geometry geometry(MULTILINESTRING,4269)
)


INFO:sqlalchemy.engine.Engine:[no key 0.00071s] {}
INFO:sqlalchemy.engine.Engine:CREATE INDEX idx_trails_geometry ON public.trails USING gist (geometry)
INFO:sqlalchemy.engine.Engine:[no key 0.00060s] {}
INFO:sqlalchemy.engine.Engine:COMMIT