In [17]:
import geopandas as gpd
import pandas as pd
import fiona
from sqlalchemy import create_engine
from geoalchemy2 import Geometry
from shapely.geometry import MultiPolygon, shape, mapping


#update the names of the lakes if we have a beter option
import sys
sys.path.insert(0, "/home/whurst/dev/water_weather_apis/")
from nationalmap import NationalMap as NatMap
import requests
NatMap.set_requester(requests)
import time

In [2]:
from pynhd import WaterData
#for streams, use nhdflowline_network
wd = WaterData("nhdwaterbody")  # or waterbody layer

43.43066392679538, -109.97236889976298
42.56832796635991, -108.89390378332534
# Query by bounding box around your point
bbox = (-109.98, 42.55, -108.89, 43.44)
# bbox = (-109.32, 42.99, -109.29, 43.02)

gdf = wd.bybox(bbox)

In [3]:
filtered_lakes = gdf[gdf["areasqkm"] > 0.01]
print(len(filtered_lakes))
filtered_lakes[['gnis_name', 'areasqkm', 'maxdepth', 'geometry', 'elevation']]

1297

,gnis_name,areasqkm,maxdepth,geometry,elevation
0,,0.017,NaN,"MULTIPOLYGON (((-108.96082 43.43547, -108.9609...",0
1,,0.070,2.748735,"MULTIPOLYGON (((-108.92104 43.43177, -108.9201...",0
2,,0.018,4.470124,"MULTIPOLYGON (((-109.09656 42.86166, -109.0971...",0
3,Sand Lake,0.042,3.068029,"MULTIPOLYGON (((-109.10592 42.85966, -109.1060...",0
4,,0.053,NaN,"MULTIPOLYGON (((-109.13228 42.85332, -109.1323...",0
...,...,...,...,...,...
1301,Sweeney Lakes,0.040,NaN,"MULTIPOLYGON (((-109.67741 42.99996, -109.6774...",0
1302,Fremont Lake,20.453,61.969615,"MULTIPOLYGON (((-109.7779 43.0243, -109.77784 ...",2261
1303,Willow Lake,7.315,54.103445,"MULTIPOLYGON (((-109.86231 42.99995, -109.8627...",2346
1304,,0.301,10.985506,"MULTIPOLYGON (((-109.45575 42.99997, -109.4560...",0
1305,,0.030,2.466010,"MULTIPOLYGON (((-109.31355 42.99997, -109.3131...",0

In [4]:
# Enable KML driver support
fiona.drvsupport.supported_drivers['KML'] = 'rw' 

# Read the KML file
winds_lakes_data = gpd.read_file('Winds_Lakes.kml', driver='KML')
winds_lakes_data

,id,Name,description,timestamp,begin,end,altitudeMode,tessellate,extrude,visibility,drawOrder,icon,Last_Confirmed,Species,Trophy_Potentiometer,Stocked_,geometry
0,None,Stonehammer,,NaT,NaT,NaT,None,-1,0,-1,NaN,None,,GD,,,POINT Z (-109.71034 43.16398 0)
1,None,Peak,,NaT,NaT,NaT,None,-1,0,-1,NaN,None,,GD,,,POINT Z (-109.70317 43.15403 0)
2,None,Elbow,,NaT,NaT,NaT,None,-1,0,-1,NaN,None,,GD,5.0,,POINT Z (-109.70307 43.12177 0)
3,None,Faler,,NaT,NaT,NaT,None,-1,0,-1,NaN,None,,GD,,,POINT Z (-109.74838 43.32154 0)
4,None,Clear,,NaT,NaT,NaT,None,-1,0,-1,NaN,None,,GD,,,POINT Z (-109.75808 43.31279 0)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,None,RH Campsite 07/2024,,NaT,NaT,NaT,None,-1,0,-1,NaN,None,,,,,POINT Z (-109.10123 42.73586 0)
174,None,RH Campsite 07/2024,,NaT,NaT,NaT,None,-1,0,-1,NaN,None,,,,,POINT Z (-109.11239 42.6816 0)
175,None,Secret Lake Outlier,Bernard (Personal communication),NaT,NaT,NaT,None,-1,0,-1,NaN,None,1752991200000000,Golden,,,POINT Z (-109.42663 43.03852 0)
176,None,Heebeecheeche,Bernard (Personal communication),NaT,NaT,NaT,None,-1,0,-1,NaN,None,1752991200000000,Lake Trout,,,POINT Z (-109.34002 42.96072 0)
177,None,Wilson Creek Lakes,"Good sized fish, per Bernard (Personal communi...",NaT,NaT,NaT,None,-1,0,-1,NaN,None,1752991200000000,Cutbows,,,POINT Z (-109.2979 43.00947 0)

In [5]:
from shapely.geometry import Point
for row in winds_lakes_data.itertuples():
    # pt = Point(lon, lat)
    
    lake = filtered_lakes[filtered_lakes.contains(row.geometry)]
    if not lake.empty:
        idx = lake.index[0]
        name = lake.at[idx, "gnis_name"]
        # print(name)
        if pd.isna(name) or name == "" or name == " ":
            print("#", lake.at[idx, "gnis_name"], idx, "!", row.Name)
            filtered_lakes.at[idx, "gnis_name"] = row.Name

#   1117 ! Elbow Creek Lake #1
#   485 ! Joe's
#   499 ! Upper Elbow (Slim)
#   519 ! Upper Twin
#   559 ! W3 / Bridger 6
#   591 ! Upper Triangle
#   502 ! Upper Titcomb
#   548 ! Pothole
#   838 ! East Fork
#   383 ! Sassafras
#   366 ! Four Creeks #4
#   365 ! Four Creeks #3
#   368 ! Four Creeks #2
#   363 ! Four Creeks
#   356 ! Rich Lake #1
#   351 ! Rich Lake #2 (10590)

#   354 ! Rich Lake #3
#   830 ! Bonneville
#   36 ! Upper Deep Creek
#   28 ! Hidden?
#   311 ! Golden (Dry Creek)
#   93 ! Windy
#   425 ! Lower Saddlebag
#   1256 ! Upper Tayo
#   218 ! Upper Valentine
#   378 ! Marked Tree
#   322 ! Rock
#   320 ! Norman
#   35 ! Heart
#   33 ! Middle Deep Creek
#   34 ! Lower Deep Creek
#   571 ! B1
#   466 ! Blucher
#   565 ! B2
#   370 ! Lake 9227
#   393 ! Knifeblade?
#   399 ! Warrior?
#   314 ! Lower Glacier Lake
#   832 ! S Fk Bldr Ck 1?
#   521 ! Elbow Ck 4 or 5
#   524 ! Elbow Ck 4 or 5
#   834 ! Jim Harrower 3?
#   90 ! Ham
#   40 ! Jug Lake
#   551 ! B5
#   556 ! B4
#   533 ! Lake 10548

#   196 ! Lake 10911

#   187 ! Lake 10885

#   1228 ! Grave Creek Lakes 2

#   185 ! Grave Creek Lakes 3

#   561 ! Point 141
#   332 ! Jog Lake (?)

#   381 ! Marys (?)

#   382 ! Peggy Lake (?)

#   1215 ! Tamoshanter (?)

#   387 ! Bear Lake (?)

#   377 ! Hook Lake (?)

#   21 ! Shelf Lake
#   386 ! Secret Lake Outlier

In [35]:
squarekm_to_acres = 247.105
table_data = gpd.GeoDataFrame({
    #table values are as follows:
    #name
    "name": filtered_lakes["gnis_name"],
    #boundary
    "boundary": filtered_lakes['geometry'],
    #nominal_coords (todo: rename centroid to nominal_coords
    # "nominal_coords": filtered_lakes['geometry'].representative_point(),
    #elevation
    # "elevation": 0,
    #surface_area
    "surface_area": filtered_lakes["areasqkm"]*squarekm_to_acres,
    #state
    "state": "WY",
    #county
    # "county": gdf["COUNTY"],
    #state_id
    # "state_id": gdf["DFGWATERID"],
    #gnis_id
    "gnis_id": filtered_lakes["gnis_id"] 
    
    }, geometry="boundary", crs = gdf.crs )



def ensure_multipolygon(geom):
    if geom.geom_type == "Polygon":
        return MultiPolygon([geom])
    return geom

table_data["boundary"] = table_data["boundary"].apply(ensure_multipolygon)

def drop_z(geom):
    return shape({
        **mapping(geom),
        "coordinates": _strip_z(mapping(geom)["coordinates"])
    })

def _strip_z(coords):
    if isinstance(coords[0], (float, int)):  # single point
        return coords[:2]
    return [_strip_z(c) for c in coords]

table_data["boundary"] = table_data["boundary"].apply(drop_z)

table_data["nominal_coords"] = table_data["boundary"].representative_point()
table_data["gnis_id"] = pd.to_numeric(
    table_data["gnis_id"].astype(str).str.strip(),
    errors="coerce"
).astype("Int64")

In [28]:
table_data.geometry

0       MULTIPOLYGON (((-108.96082 43.43547, -108.9609...
1       MULTIPOLYGON (((-108.92104 43.43177, -108.9201...
2       MULTIPOLYGON (((-109.09656 42.86166, -109.0971...
3       MULTIPOLYGON (((-109.10592 42.85966, -109.1060...
4       MULTIPOLYGON (((-109.13228 42.85332, -109.1323...
                              ...
1301    MULTIPOLYGON (((-109.67741 42.99996, -109.6774...
1302    MULTIPOLYGON (((-109.7779 43.0243, -109.77784 ...
1303    MULTIPOLYGON (((-109.86231 42.99995, -109.8627...
1304    MULTIPOLYGON (((-109.45575 42.99997, -109.4560...
1305    MULTIPOLYGON (((-109.31355 42.99997, -109.3131...
Name: boundary, Length: 1297, dtype: geometry

In [10]:

for row in table_data.itertuples():
    request = NatMap.ElevationRequest(row.nominal_coords.x, row.nominal_coords.y)
    table_data.at[row.idx, 'elevation'] = NatMap.send_request(request)
    time.sleep(0.1)
    print("got 'em")

HTTPError: 500 Server Error: Internal Server Error for url: https://epqs.nationalmap.gov/v1/json?x=-108.96036996082307&y=43.436273&units=Feet&output=json

In [31]:
table_data['gnis_id']

0
1
2
3       1593900
4
         ...
1301    1603479
1302    1609181
1303    1604220
1304
1305
Name: gnis_id, Length: 1297, dtype: str

In [29]:
print(type(table_data))
print("geometry column:", table_data.geometry.name)
print("active geometry:", table_data._geometry_column_name)
print("is geodataframe:", hasattr(table_data, "geometry"))

<class 'geopandas.geodataframe.GeoDataFrame'>
geometry column: boundary
active geometry: boundary
is geodataframe: True

In [23]:
print(type(table_data["nominal_coords"].iloc[0]))

<class 'shapely.geometry.point.Point'>

In [24]:
import logging
import os

logging.basicConfig()
logging.getLogger('sqlalchemy.engine').setLevel(logging.DEBUG)
# --- database connection ---
db_user = os.environ.get("TERA_DB_USR")
db_pswrd = os.environ.get("TERA_DB_PSWRD")
engine = create_engine(f"postgresql+psycopg2://{db_user}:{db_pswrd}@localhost/tera")

with engine.connect() as con:
    print("Connected!")

INFO:sqlalchemy.engine.Engine:select pg_catalog.version()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('version',)
DEBUG:sqlalchemy.engine.Engine:Row ('PostgreSQL 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit',)
INFO:sqlalchemy.engine.Engine:select current_schema()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('current_schema',)
DEBUG:sqlalchemy.engine.Engine:Row ('public',)
INFO:sqlalchemy.engine.Engine:show standard_conforming_strings
INFO:sqlalchemy.engine.Engine:[raw sql] {}
DEBUG:sqlalchemy.engine.Engine:Col ('standard_conforming_strings',)
DEBUG:sqlalchemy.engine.Engine:Row ('on',)

Connected!

In [36]:
# upload to PostGIS

try:
    table_data.to_postgis(
        name="water_bodies",
        con=engine,
        if_exists="append",
        index=False,
        dtype={
            "boundary": Geometry("MULTIPOLYGON", srid=4326),
            "nominal_coords": Geometry("POINT", srid=4326)
        }
    )
except Exception as e:
    import traceback
    traceback.print_exc()

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[cached since 1110s ago] {'table_name': 'water_bodies', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
DEBUG:sqlalchemy.engine.Engine:Row ('water_bodies',)
INFO:sqlalchemy.engine.Engine:SELECT Find_SRID(%(schema_name)s, %(name)s, %(geom_name)s);
INFO:sqlalchemy.engine.Engine:[cached since 1110s ago] {'schema_name': 'public', 'name': 'water_bodies', 'geom_name': 'boundary'}
DEBUG:sqlalchemy.engine.Engine:Col ('find_srid',)
DEBUG:sqlalchemy.engine.Engine:Row (4326,)
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[cached since 1110s ago] {'table_name': 'water_bodies', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'public'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
DEBUG:sqlalchemy.engine.Engine:Row ('water_bodies',)
INFO:sqlalchemy.engine.Engine:COMMIT

In [12]:
table_data

,name,boundary,nominal_coords,elevation,surface_area,state,county,state_id,gnis_id
0,,"MULTIPOLYGON Z (((-122.6329 41.99307 0, -122.6...",POINT (-122.63469 41.99551),2832,12.647377,CA,Siskiyou,2,0
1,Azalea Lake,"MULTIPOLYGON Z (((-123.30004 41.96928 0, -123....",POINT (-123.30053 41.96988),5383,4.601394,CA,Siskiyou,5,256390
2,White Lake,"MULTIPOLYGON Z (((-121.64563 41.99942 0, -121....",POINT (-121.63324 41.99478),4093,814.471819,CA,Siskiyou,9,269006
3,Bear Wallow,"MULTIPOLYGON Z (((-123.65463 41.95017 0, -123....",POINT (-123.65479 41.95033),4380,0.292219,CA,Del Norte,35,256730
4,Mud Lake,"MULTIPOLYGON Z (((-121.98281 41.98446 0, -121....",POINT (-121.98372 41.98555),4763,11.463147,CA,Siskiyou,39,1657412
...,...,...,...,...,...,...,...,...,...
27501,,"MULTIPOLYGON Z (((-115.46938 32.99405 0, -115....",POINT (-115.46978 32.99283),-147,15.538655,CA,Imperial,7792,0
27502,Clover Creek Pond,"MULTIPOLYGON Z (((-122.31356 40.55139 0, -122....",POINT (-122.31361 40.55054),500,9.408521,CA,Shasta,28569,0
27503,Battle Creek Pond,"MULTIPOLYGON Z (((-122.17572 40.38907 0, -122....",POINT (-122.17561 40.38861),430,3.393287,CA,Tehama,28568,0
27504,Sycamore Island Pond,"MULTIPOLYGON Z (((-119.82334 36.85213 0, -119....",POINT (-119.82595 36.85164),265,34.781933,CA,Madera,28570,0
27505,Libby Water,"MULTIPOLYGON Z (((-120.47625 38.1052 0, -120.4...",POINT (-120.47638 38.10502),2000,0.552185,CA,Calaveras,28572,0

In [13]:
missing = survey_data.loc[~survey_data['CaLakesID'].isin(table_data['state_id'])]
acres_per_hectare = 2.47105
missing_table_data = gpd.GeoDataFrame({
    #table values are as follows:
    #name
    "name": missing["LakeName"],
    #nominal_coords (todo: rename centroid to nominal_coords
    "nominal_coords": missing["geometry"],
    #surface_area
    "surface_area": missing["AreaHectares"]*acres_per_hectare,
    #state
    "state": "CA",
    #state_id
    "state_id": missing["CaLakesID"],
    
    }, geometry="nominal_coords", crs = gdf.crs )

missing_table_data= missing_table_data.drop_duplicates()

In [14]:
missing_table_data

,name,nominal_coords,surface_area,state,state_id
140,Lake Katherine,POINT (-123.21702 41.45322),5.411599,CA,333
648,Grouse Creek Lake,POINT (-119.71149 38.24764),4.942100,CA,3256
751,NaN,POINT (-121.35895 40.128),0.098842,CA,11738
1099,NaN,POINT (-120.55812 39.41173),0.494210,CA,12693
1488,NaN,POINT (-120.17055 38.87779),0.296526,CA,14142
...,...,...,...,...,...
4036,NaN,POINT (-120.48265 39.36831),0.988420,CA,52594
4037,"Mulkey Creek, Middle",POINT (-118.16059 36.40935),2.174524,CA,52634
4038,NaN,POINT (-118.80654 37.39625),0.395368,CA,52652
4039,Ball's Canyon Creek,POINT (-120.05319 39.6563),0.494210,CA,52653
4040,Last Chance Creek,POINT (-120.48563 40.11205),0.889578,CA,52654

In [15]:
try:
    missing_table_data.to_postgis(
        name="water_bodies",
        con=engine,
        if_exists="append",
        index=False,
        dtype={
            "nominal_coords": Geometry("POINT", srid=4326)
        }
    )
except Exception as e:
    import traceback
    traceback.print_exc()

INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[cached since 16.38s ago] {'table_name': 'water_bodies', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
DEBUG:sqlalchemy.engine.Engine:Row ('water_bodies',)
INFO:sqlalchemy.engine.Engine:SELECT Find_SRID(%(schema_name)s, %(name)s, %(geom_name)s);
INFO:sqlalchemy.engine.Engine:[generated in 0.00263s] {'schema_name': 'public', 'name': 'water_bodies', 'geom_name': 'nominal_coords'}
DEBUG:sqlalchemy.engine.Engine:Col ('find_srid',)
DEBUG:sqlalchemy.engine.Engine:Row (4326,)
INFO:sqlalchemy.engine.Engine:COMMIT
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_namespace.nspname = %(nspname_1)s
INFO:sqlalchemy.engine.Engine:[cached since 16.43s ago] {'table_name': 'water_bodies', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'public'}
DEBUG:sqlalchemy.engine.Engine:Col ('relname',)
DEBUG:sqlalchemy.engine.Engine:Row ('water_bodies',)
INFO:sqlalchemy.engine.Engine:COMMIT

In [ ]:
#then run this command to add the index column
ALTER TABLE water_bodies
ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY;


#then run
UPDATE water_bodies SET name = NULL WHERE name = ' ';